import { hashPassword } from "../src/utils/password";
import { validatePassword } from "../src/utils/validation";

const ADMIN_SEED_EMAIL = "admin@monster7.dev";
const ADMIN_SEED_ID = "00000000-0000-4000-8000-000000000001";

const getRequiredEnv = (key: string): string => {
  const value = process.env[key]?.trim();

  if (!value) {
    throw new Error(`${key} is required for admin seed.`);
  }

  return value;
};

const run = async () => {
  const password = getRequiredEnv("ADMIN_SEED_PASSWORD");

  if (!validatePassword(password)) {
    throw new Error(
      "ADMIN_SEED_PASSWORD must be at least 8 characters and include uppercase, lowercase, and numbers.",
    );
  }

  const passwordHash = await hashPassword(password);
  const timestamp = new Date().toISOString();

  console.log(`
INSERT INTO users (
  id,
  email,
  password_hash,
  name,
  bio,
  avatar_url,
  role,
  is_active,
  created_at,
  updated_at
) VALUES (
  '${ADMIN_SEED_ID}',
  '${ADMIN_SEED_EMAIL}',
  '${passwordHash}',
  'Monster7 Admin',
  'Initial admin account generated by seed.ts',
  NULL,
  'admin',
  1,
  '${timestamp}',
  '${timestamp}'
) ON CONFLICT(email) DO UPDATE SET
  password_hash = excluded.password_hash,
  name = excluded.name,
  bio = excluded.bio,
  role = excluded.role,
  is_active = excluded.is_active,
  updated_at = excluded.updated_at;
  `.trim());
};

void run();
