name = "monster7-member-api"
main = "src/index.ts"
compatibility_date = "2026-03-20"
workers_dev = true

[vars]
ENVIRONMENT = "staging"
APP_URL = "https://main.monster7-member-dfm.pages.dev"
API_URL = "https://monster7-member-api.cosima-monster7.workers.dev"
R2_PUBLIC_URL = "https://pub-4d2519ac922146d59e00a76faa46513e.r2.dev"
ALLOWED_ORIGINS = "https://main.monster7-member-dfm.pages.dev,http://localhost:5173,http://127.0.0.1:5173"

[[d1_databases]]
binding = "DB"
database_name = "monster7-db-staging"
database_id = "92cf3771-9e87-477c-a55c-d6fe71ffc25f"
migrations_dir = "./migrations"

[[kv_namespaces]]
binding = "KV"
id = "e52a179805b444c9b56ac37710c24786"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "monster7-bucket-staging"
preview_bucket_name = "monster7-bucket-staging"

[env.production]
name = "monster7-member-api-production"

[env.production.vars]
ENVIRONMENT = "production"
APP_URL = "https://monster7-member-dfm.pages.dev"
API_URL = "https://monster7-member-api-production.cosima-monster7.workers.dev"
R2_PUBLIC_URL = "https://pub-8b0b658cebf647dc9791fe51d7f406ba.r2.dev"
ALLOWED_ORIGINS = "https://monster7-member-dfm.pages.dev"

[[env.production.d1_databases]]
binding = "DB"
database_name = "monster7-db-production"
database_id = "7b080645-cf2f-400a-84b6-c1394103f7e1"
migrations_dir = "./migrations"

[[env.production.kv_namespaces]]
binding = "KV"
id = "34bc3de8bb5f48269f24048594c5baa8"

[[env.production.r2_buckets]]
binding = "BUCKET"
bucket_name = "monster7-bucket-production"
preview_bucket_name = "monster7-bucket-production"
